export enum TIPO_NATIVA_CADENA{
    TOLOWER,
    TOUPPER,
    LENGHT,
    SUBSTRING,
    CARACTER_POSITION,
    REPETICION,
    INTPARSE,
    DOUBLEPARSE,
    BOOLEANPARSE,
    TOINT,
    TOSTRING,
    TODOUBLE,
    STRING,
    TYPEOF,

}